# conda env create -f environment.yml -n ...

channels:
    - conda-forge

dependencies:
    - pip
    - python=3.8
    - h5py
    - rdkit
    - pandas
    - numpy
    - scipy
    
    - pip:
        - data-CAT@git+https://github.com/nlesc-nano/data-CAT@master
        - nano-CAT@git+https://github.com/nlesc-nano/nano-CAT@master
        - plams@git+https://github.com/SCM-NV/PLAMS@a5696ce62c09153a9fa67b2b03a750913e1d0924
        - qmflows@git+https://github.com/SCM-NV/qmflows@master

