# conda env create -f environment.yml -n ...

channels:
    - conda-forge

dependencies:
    - pip
    - python=3.8
    - h5py
    - rdkit

    - pip:
        - data-CAT@git+https://github.com/nlesc-nano/data-CAT@master
        - nano-CAT@git+https://github.com/nlesc-nano/nano-CAT@master

