from typing import Mapping, Tuple, List

__all__: List[str] = ...

KEY_MAP: Mapping[str, Tuple[str, str]] = ...

OPT: Tuple[str, str] = ...
MOL: Tuple[str, str] = ...
FORMULA: Tuple[str, str] = ...
HDF5_INDEX: Tuple[str, str] = ...
JOB_SETTINGS_QD_OPT: Tuple[str, str] = ...
JOB_SETTINGS_CRS: Tuple[str, str] = ...
JOB_SETTINGS_BDE: Tuple[str, str] = ...
JOB_SETTINGS_ASA: Tuple[str, str] = ...
ASA_INT: Tuple[str, str] = ...
ASA_STRAIN: Tuple[str, str] = ...
ASA_E: Tuple[str, str] = ...
SETTINGS1: Tuple[str, str] = ...
SETTINGS2: Tuple[str, str] = ...
SETTINGS_SOLV1: Tuple[str, str] = ...
SETTINGS_SOLV2: Tuple[str, str] = ...
SETTINGS_ASA: Tuple[str, str] = ...
SETTINGS_BDE1: Tuple[str, str] = ...
SETTINGS_BDE2: Tuple[str, str] = ...
V_BULK: Tuple[str, str] = ...
