path: /Users/basvanbeek/Documents/CdSe/Week_5

input_cores:
    - Cd68Se55.xyz:
        guess_bonds: False

input_ligands:
    - 'COc1cc[C[=O]O[C@H][C[=O]O][C@H][OC[=O]c2ccc[OC[C]=O]c[OC]c2]C[=O]Nc2ccc[N=Nc3ccccc3]cc2]ccc1OC[C]=O'

optional:
    database:
        dirname: database
        read: True
        write: True
        overwrite: False
        mol_format: [pdb]
        mongodb: False

    core:
        dirname: core
        dummy: Cl

    ligand:
        dirname: ligand
        optimize: True
        split: True
        functional_groups: 'O(C=O)[H]'
        cosmo-rs: False

    qd:
        dirname: QD
        construct_qd: True
        optimize: False
        bulkiness: False
        activation_strain: False
